server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/twitterdb
    username: postgres
    password: password
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    generate-ddl: true
    format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      fail_on_empty_beans: false

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: INFO
        data: INFO
app:
  frontend-basepath: http://localhost:3000
  secret: secret