server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/twitterdb
    username: postgres
    password: password
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      fail_on_empty_beans: false

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: INFO
        data: INFO
    com:
      frederikzwartbol:
        springboottwitterrebuild: DEBUG
app:
  frontend-basepath: http://localhost:3000
  secret: secret