spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/twitterdb
    username: postgres
    password: password
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      fail_on_empty_beans: false
logging:
  level:
    org:
      hibernate:
        type: trace
app:
  frontend-basepath: http://localhost:3000
  secret: secretpassword